Quizzer/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataManager;
using Microsoft.AspNet.Identity;
using Quizzer.Models;
using WebGrease.Css.Extensions;

namespace Quizzer.Controllers
{
    [Authorize(Roles = "Student")]
    public class QuizController : Controller
    {
        private DomainService _domainService = new DomainService();
        private QuizService _quizService = new QuizService();
        private Random _random = new Random(DateTime.Now.Millisecond);

        public ActionResult Index()
        {
            var domains = _domainService.GetDomains().ToList();
            var quizes = _quizService.GetForUser(User.Identity.GetUserId()).ToList().Select(x => new QuizModel(x)).ToList();

            return View(new QuizDomainModel()
            {
                Domains = domains,
                Quizes = quizes
            });
        }

        public ActionResult GetQuiz(int domainId)
        {
            var quizSets = _quizService.GetForUser(User.Identity.GetUserId()).Where(x => x.DomainId == domainId && x.Status == 1 && DateTime.Now < x.DateLimit).ToList();
            if (quizSets.Any())
            {
                return RedirectToAction("TakeQuiz", new { id = quizSets.First().Id.ToString()});
            }

            var simpleCount = 3 + _random.Next(2);
            var domain = _domainService.GetDomains().First(x => x.Id == domainId);

            var simpleQuestions =
                domain.SubDomains.SelectMany(s => s.QuizItems)
                    .Where(q => !q.HasManyAnswers)
                    .OrderBy(x => _random.NextDouble())
                    .Take(simpleCount).ToList();

            var multipleQuestions = domain.SubDomains.SelectMany(s => s.QuizItems)
                    .Where(q => q.HasManyAnswers)
                    .OrderBy(x => _random.NextDouble())
                    .Take(10 - simpleCount).ToList();

            var questions = new List<QuizItem>(simpleQuestions);
            questions.AddRange(multipleQuestions);
            questions = questions.OrderBy(x => _random.NextDouble()).ToList();

            var quiz = _quizService.GenerateQuiz(User.Identity.GetUserId(), questions, domainId);
            var newQuiz = _quizService.GetForUser(User.Identity.GetUserId()).First(x => x.Id == quiz.Id);

            return RedirectToAction("TakeQuiz", new { id = newQuiz.Id.ToString()});
        }
        
        [RestoreModelStateFromTempData]
        public ActionResult TakeQuiz(string id, int page = 0)
        {
            var guid = Guid.Parse(id);
            var quiz =
                _quizService.GetForUser(User.Identity.GetUserId())
                    .First(x => x.Id == guid);
            var questions = quiz.QuizSetQuestions.Select(x => new QuestionModel()
            {
                Id = x.QuizItem.Id.ToString(),
                Text = x.QuizItem.Description,
                IsAnswered = quiz.QuizSetAnswers.Any(y => y.QuizItemId == x.QuizItemId)
            }).ToList();

            var model = new QuizQuestionModel();
            model.Questions = questions;

            model.QuizSetId = quiz.Id.ToString();
            var domain = _domainService.GetDomains().First(x => x.Id == quiz.DomainId);
            model.DomainName = domain != null ? domain.Name : "";

            model.ReadOnly = quiz.Status > 1 || quiz.DateLimit < DateTime.Now;
            model.DateLimit = quiz.DateLimit;

            if (page >= 1 && page <= 10)
            {
                var question = quiz.QuizSetQuestions.ElementAt(page - 1);

                model.QuestionId = question.QuizItemId.ToString();
                model.QuestionText = question.QuizItem.Description;
                model.IsWithMultipleChoice = question.QuizItem.HasManyAnswers;
                model.Page = page;
                model.QuizSetId = quiz.Id.ToString();

                var answers = question.QuizItem.Answers.Select(x => new QuizAnswerModel()
                {
                    Id = x.Id.ToString(),
                    Text = x.Description,
                    IsSelected = quiz.QuizSetAnswers.Any(y => y.AnswerId == x.Id)
                }).ToList();

                model.IsAnswered = answers.Any(x => x.IsSelected);
                model.Answers = answers;

                if (!model.IsWithMultipleChoice && model.Answers.Any(x => x.IsSelected))
                    model.SelectedAnswer = model.Answers.First(x => x.IsSelected).Id;
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SetTempDataModelState]
        public ActionResult EndQuiz(string id)
        {
            var guid = Guid.Parse(id);
            ComputeScore(guid);

            return RedirectToAction("TakeQuiz", new { id = guid.ToString()});
        }

        private void ComputeScore(Guid guid)
        {
            var quiz =
                _quizService.GetForUser(User.Identity.GetUserId())
                    .First(x => x.Id == guid);

            var score = 0.0;
            foreach (var question in quiz.QuizSetAnswers)
            {
                var questionScore = 0.0;

                var givenAnswers =
                    quiz.QuizSetAnswers.Where(x => x.QuizItemId == question.QuizItemId).Select(x => x.AnswerId).ToList();
                var correctAnswers = question.QuizItem.Answers.Where(x => x.IsCorrect).Select(x => x.Id).ToList();
                foreach (var answerId in givenAnswers)
                {
                    questionScore += correctAnswers.Any(x => x.Equals(answerId)) ? 1 : -1;
                }

                if (questionScore > 0)
                    score += questionScore/correctAnswers.Count;
            }

            _quizService.UpdateQuizScore(quiz, score);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SetTempDataModelState]
        public ActionResult SaveQuizAnswer(QuizQuestionModel model)
        {
            var guid = Guid.Parse(model.QuizSetId);
            var quizItem = _quizService.GetForUser(User.Identity.GetUserId()).First(x => x.Id == guid);

            if (quizItem.Status > 1)
            {
                ModelState.AddModelError("expired", "You can no longer change your answer");
            }

            if (quizItem.DateLimit < DateTime.Now)
            {
                ModelState.AddModelError("timeExceeded", "You have exceeded the time limit");
                ComputeScore(guid);
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("TakeQuiz", new { id = model.QuizSetId, page = model.Page });
            }

            if (!model.IsWithMultipleChoice)
            {
                if (string.IsNullOrWhiteSpace(model.SelectedAnswer))
                {
                    ModelState.AddModelError("noAnswerSelected", "You must select an answer");
                }
                else
                {
                    var answer = new QuizSetAnswer()
                    {
                        AnswerId = Guid.Parse(model.SelectedAnswer),
                        QuizItemId = Guid.Parse(model.QuestionId),
                        QuizSetId = quizItem.Id
                    };

                    _quizService.SaveAnswer(answer);
                }
            }
            else
            {
                if (!model.Answers.Any(x => x.IsSelected))
                {
                    ModelState.AddModelError("noAnswerSelected", "You must select an answer");
                }
                else
                {
                    var answers = model.Answers.Where(x => x.IsSelected).Select(x => new QuizSetAnswer()
                    {
                        AnswerId = Guid.Parse(x.Id),
                        QuizItemId = Guid.Parse(model.QuestionId),
                        QuizSetId = quizItem.Id
                    }).ToList();

                    _quizService.SaveAnswers(answers);
                }
            }

            return RedirectToAction("TakeQuiz", new {id = model.QuizSetId, page = model.Page});
        }
	}
}

Quizzer/Views/Quiz/Index.cshtml
@model Quizzer.Models.QuizDomainModel

@{
    ViewBag.Title = "Index Quiz";
}

<div class="container">
    <h2>@ViewBag.Title</h2>

    <table class="table table-hover">
        <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th></th>
        </tr>
        </thead>
        <tbody id="domainTable">
        @foreach (var domain in Model.Domains)
        {
            <tr class="domainRow" onclick="toggle(@domain.Id)">
                <td>@domain.Name</td>
                <td>@domain.Description</td>
                <td>@Html.ActionLink("Take new quiz", "GetQuiz", new {domainId = domain.Id}, new {@class = "btn btn-default"})</td>
            </tr>
            foreach (var quiz in Model.Quizes.Where(x => x.DomainId == domain.Id))
            {
                <tr class="collapse row_@domain.Id ">
                    <td>@quiz.Date</td>
                    <td>@quiz.Score / 10 pts</td>
                    <td>
                        @Html.ActionLink(quiz.ReadOnly ? "View" : "Continue" + " quiz", "TakeQuiz", new { id = @quiz.Id.ToString() }, new { @class = "btn btn-default" })
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>
@section scripts
{
    <script>
       function toggle(id) {
            $('tr.collapse').hide();
            var rows = $('.row_' + id);
            rows.toggle('slow');
        }
    </script>
}

Quizzer/Views/Quiz/TakeQuiz.cshtml
@model Quizzer.Models.QuizQuestionModel

@{
    ViewBag.Title = "Quiz: " + Model.DomainName;
}

<div class="container">
    <h2>
        @ViewBag.Title
        @if(!Model.ReadOnly){ 
        <span class="float-right">
        Time limit:
        <span id="timer"></span>
        @Html.Hidden("timeLimit", Model.DateLimit.ToUniversalTime().Subtract(new DateTime(1970, 1, 1)).TotalMilliseconds)
        </span>
        }
    </h2>
<br />
@if (Model.Answers == null)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Questions</h3>
        </div>
        <div class="panel-body">
            <table class="table table-hover">
                @for (var i = 1; i <= 10; i++)
                {
                    <tr>
                        <td>
                            <a href="?page=@i" class="@(Model.Questions[i - 1].IsAnswered ? "answered" : "unanswered")">@i.ToString(). @Model.Questions[i - 1].Text</a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
}
else
{
    <div class="container col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><a href="?page=0" class="bold">Questions</a>: @string.Format("{0}/10 answered", Model.Questions.Count(x => x.IsAnswered))</h3>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                    @for (var i = 1; i <= 10; i++)
                    {
                        <li class="list-group-item">
                            <a href="?page=@i" class="@(Model.Questions[i - 1].IsAnswered ? "answered" : "unanswered")">@i.ToString(). @string.Join("", Model.Questions[i - 1].Text.Take(70))...</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container col-md-8">
        @using (Html.BeginForm("SaveQuizAnswer", "Quiz"))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary(false)

                @Html.HiddenFor(model => model.QuestionId)
                @Html.HiddenFor(model => model.IsWithMultipleChoice)
                @Html.HiddenFor(model => model.QuizSetId)
                @Html.HiddenFor(model => model.Page)
                <div class="container">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title bold">@Model.Page. @Model.QuestionText</h3>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group">
                                @for (var index = 0; index < Model.Answers.Count; index++)
                                {
                                    @Html.HiddenFor(model => model.Answers[index].Id)
                                    <li class="list-group-item">
                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                @if (Model.IsWithMultipleChoice)
                                                {
                                                    @Html.CheckBoxFor(model => model.Answers[index].IsSelected, new { @class = "checker", disabled = Model.ReadOnly })
                                                }
                                                else
                                                {
                                                    @Html.RadioButtonFor(model => model.SelectedAnswer, Model.Answers[index].Id, new { @class = "checker", disabled = Model.ReadOnly })
                                                }
                                            </span>
                                            <input type="text" class="form-control" readonly value="@Model.Answers[index].Text" />
                                        </div>
                                    </li>
                                }
                            </ul>
                            <div class="row">
                                <div class="col-md-4">
                                    <a href="?page=@(Model.Page - 1)" class="btn btn-default float-left">Previous</a>
                                </div>
                                <div class="col-md-4 text-center">
                                    <input type="submit" id="saveAnswer" class="btn btn-primary" value="Save answer" @(Model.IsAnswered || Model.ReadOnly ? "disabled" : "") />
                                </div>
                                @if (Model.Page < 10)
                                {
                                    <div class="col-md-4">
                                        <a href="?page=@(Model.Page + 1)" class="btn btn-default float-right">Next</a>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
        @if (!Model.ReadOnly)
        {
            <div class="col-md-2">
                @using (Html.BeginForm("EndQuiz", "Quiz", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("id", Model.QuizSetId)
                    <input type="submit" class="btn btn-success float-right" value="End quiz" />
                }
            </div>
        }

    </div>
}
</div>



@section scripts
{
    <script>
        function QuizTimer() {
            var time = new Date(parseInt($('#timeLimit').val()));
            var timeSpan = moment(time).countdown().toString();
            $('#timer').text(timeSpan);
        }

        $(document).ready(function() {
            var interval = setInterval(function () { QuizTimer() }, 1000);
            console.log(new Date($('#timeLimit').val()));
            $('.checker').change(function() {
                $('#saveAnswer').removeAttr('disabled');
            });
        });
    </script>
}